// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlaybackStatus playback status
//
// swagger:model PlaybackStatus
type PlaybackStatus struct {

	// 数据库 session 表中的 session 字段
	// Example: 7210000
	// Required: true
	SessionID *string `json:"sessionId"`

	//  回放状态信息: <br> playbackNotGenerated 回放还未生成, 包括需要重新生成, 还未生成 <br> sessionNotExist 课程不存在 <br> sessionNotFinish 课程正在上课 <br> playbackFailedGenerated 回放生成失败, 包括只有语音、只有画图等各种错误情况 <br> playbackSuccessGenerated 回放生成成功
	// Example: playbackSuccessGenerated
	// Required: true
	// Enum: [sessionNotExist sessionNotFinish playbackNotGenerated playbackFailedGenerated playbackSuccessGenerated]
	Status *string `json:"status"`
}

// Validate validates this playback status
func (m *PlaybackStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSessionID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlaybackStatus) validateSessionID(formats strfmt.Registry) error {

	if err := validate.Required("sessionId", "body", m.SessionID); err != nil {
		return err
	}

	return nil
}

var playbackStatusTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["sessionNotExist","sessionNotFinish","playbackNotGenerated","playbackFailedGenerated","playbackSuccessGenerated"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		playbackStatusTypeStatusPropEnum = append(playbackStatusTypeStatusPropEnum, v)
	}
}

const (

	// PlaybackStatusStatusSessionNotExist captures enum value "sessionNotExist"
	PlaybackStatusStatusSessionNotExist string = "sessionNotExist"

	// PlaybackStatusStatusSessionNotFinish captures enum value "sessionNotFinish"
	PlaybackStatusStatusSessionNotFinish string = "sessionNotFinish"

	// PlaybackStatusStatusPlaybackNotGenerated captures enum value "playbackNotGenerated"
	PlaybackStatusStatusPlaybackNotGenerated string = "playbackNotGenerated"

	// PlaybackStatusStatusPlaybackFailedGenerated captures enum value "playbackFailedGenerated"
	PlaybackStatusStatusPlaybackFailedGenerated string = "playbackFailedGenerated"

	// PlaybackStatusStatusPlaybackSuccessGenerated captures enum value "playbackSuccessGenerated"
	PlaybackStatusStatusPlaybackSuccessGenerated string = "playbackSuccessGenerated"
)

// prop value enum
func (m *PlaybackStatus) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, playbackStatusTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PlaybackStatus) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this playback status based on context it is used
func (m *PlaybackStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlaybackStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlaybackStatus) UnmarshalBinary(b []byte) error {
	var res PlaybackStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
