// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Test.proto

package ProtoBuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// option go_package="D:/GoProgram/src/go_learn/ProtoBuf";
type Person struct {
	Name                 *string  `protobuf:"bytes,1,req,name=Name" json:"Name,omitempty"`
	Age                  *int32   `protobuf:"varint,2,req,name=Age" json:"Age,omitempty"`
	From                 *string  `protobuf:"bytes,3,req,name=From" json:"From,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d72138f86b68d38, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *Person) GetFrom() string {
	if m != nil && m.From != nil {
		return *m.From
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "ProtoBuf.Person")
}

func init() { proto.RegisterFile("Test.proto", fileDescriptor_7d72138f86b68d38) }

var fileDescriptor_7d72138f86b68d38 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x08, 0x00, 0x51, 0x4e, 0xa5, 0x69, 0x4a, 0x4e,
	0x5c, 0x6c, 0x01, 0xa9, 0x45, 0xc5, 0xf9, 0x79, 0x42, 0x42, 0x5c, 0x2c, 0x7e, 0x89, 0xb9, 0xa9,
	0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17, 0xb3, 0x63, 0x7a, 0xaa,
	0x04, 0x93, 0x02, 0x93, 0x06, 0x6b, 0x10, 0x88, 0x09, 0x52, 0xe5, 0x56, 0x94, 0x9f, 0x2b, 0xc1,
	0x0c, 0x51, 0x05, 0x62, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x61, 0x95, 0x5f, 0x5a, 0x00,
	0x00, 0x00,
}
