// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"courseWork/cmd/models"
)

// GetPlaybackStatusesBySessionIdsReader is a Reader for the GetPlaybackStatusesBySessionIds structure.
type GetPlaybackStatusesBySessionIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlaybackStatusesBySessionIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGetPlaybackStatusesBySessionIdsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetPlaybackStatusesBySessionIdsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPlaybackStatusesBySessionIdsCreated creates a GetPlaybackStatusesBySessionIdsCreated with default headers values
func NewGetPlaybackStatusesBySessionIdsCreated() *GetPlaybackStatusesBySessionIdsCreated {
	return &GetPlaybackStatusesBySessionIdsCreated{}
}

/* GetPlaybackStatusesBySessionIdsCreated describes a response with status code 201, with default header values.

请求成功
*/
type GetPlaybackStatusesBySessionIdsCreated struct {
	Payload *GetPlaybackStatusesBySessionIdsCreatedBody
}

func (o *GetPlaybackStatusesBySessionIdsCreated) Error() string {
	return fmt.Sprintf("[POST /playbackStatuses][%d] getPlaybackStatusesBySessionIdsCreated  %+v", 201, o.Payload)
}
func (o *GetPlaybackStatusesBySessionIdsCreated) GetPayload() *GetPlaybackStatusesBySessionIdsCreatedBody {
	return o.Payload
}

func (o *GetPlaybackStatusesBySessionIdsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlaybackStatusesBySessionIdsCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlaybackStatusesBySessionIdsInternalServerError creates a GetPlaybackStatusesBySessionIdsInternalServerError with default headers values
func NewGetPlaybackStatusesBySessionIdsInternalServerError() *GetPlaybackStatusesBySessionIdsInternalServerError {
	return &GetPlaybackStatusesBySessionIdsInternalServerError{}
}

/* GetPlaybackStatusesBySessionIdsInternalServerError describes a response with status code 500, with default header values.

服务器内部异常
*/
type GetPlaybackStatusesBySessionIdsInternalServerError struct {
	Payload *models.Error
}

func (o *GetPlaybackStatusesBySessionIdsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /playbackStatuses][%d] getPlaybackStatusesBySessionIdsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetPlaybackStatusesBySessionIdsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPlaybackStatusesBySessionIdsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPlaybackStatusesBySessionIdsCreatedBody get playback statuses by session ids created body
swagger:model GetPlaybackStatusesBySessionIdsCreatedBody
*/
type GetPlaybackStatusesBySessionIdsCreatedBody struct {

	// data
	Data []*models.PlaybackStatus `json:"data"`

	// 对结果的描述
	// Example: 获取成功
	Msg string `json:"msg,omitempty"`

	// 结果情况, success 代表成功, 其他 代表失败
	// Example: success
	// Enum: [success fail]
	Result string `json:"result,omitempty"`
}

// Validate validates this get playback statuses by session ids created body
func (o *GetPlaybackStatusesBySessionIdsCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlaybackStatusesBySessionIdsCreatedBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPlaybackStatusesBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getPlaybackStatusesBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var getPlaybackStatusesBySessionIdsCreatedBodyTypeResultPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["success","fail"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getPlaybackStatusesBySessionIdsCreatedBodyTypeResultPropEnum = append(getPlaybackStatusesBySessionIdsCreatedBodyTypeResultPropEnum, v)
	}
}

const (

	// GetPlaybackStatusesBySessionIdsCreatedBodyResultSuccess captures enum value "success"
	GetPlaybackStatusesBySessionIdsCreatedBodyResultSuccess string = "success"

	// GetPlaybackStatusesBySessionIdsCreatedBodyResultFail captures enum value "fail"
	GetPlaybackStatusesBySessionIdsCreatedBodyResultFail string = "fail"
)

// prop value enum
func (o *GetPlaybackStatusesBySessionIdsCreatedBody) validateResultEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getPlaybackStatusesBySessionIdsCreatedBodyTypeResultPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetPlaybackStatusesBySessionIdsCreatedBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	// value enum
	if err := o.validateResultEnum("getPlaybackStatusesBySessionIdsCreated"+"."+"result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get playback statuses by session ids created body based on the context it is used
func (o *GetPlaybackStatusesBySessionIdsCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlaybackStatusesBySessionIdsCreatedBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPlaybackStatusesBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getPlaybackStatusesBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPlaybackStatusesBySessionIdsCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlaybackStatusesBySessionIdsCreatedBody) UnmarshalBinary(b []byte) error {
	var res GetPlaybackStatusesBySessionIdsCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
