// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"courseWork/cmd/models"
)

// GetAllTeachersByStatusReader is a Reader for the GetAllTeachersByStatus structure.
type GetAllTeachersByStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllTeachersByStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllTeachersByStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAllTeachersByStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllTeachersByStatusOK creates a GetAllTeachersByStatusOK with default headers values
func NewGetAllTeachersByStatusOK() *GetAllTeachersByStatusOK {
	return &GetAllTeachersByStatusOK{}
}

/* GetAllTeachersByStatusOK describes a response with status code 200, with default header values.

请求成功
*/
type GetAllTeachersByStatusOK struct {
	Payload *GetAllTeachersByStatusOKBody
}

func (o *GetAllTeachersByStatusOK) Error() string {
	return fmt.Sprintf("[GET /teachers/{teacherStatus}][%d] getAllTeachersByStatusOK  %+v", 200, o.Payload)
}
func (o *GetAllTeachersByStatusOK) GetPayload() *GetAllTeachersByStatusOKBody {
	return o.Payload
}

func (o *GetAllTeachersByStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetAllTeachersByStatusOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllTeachersByStatusInternalServerError creates a GetAllTeachersByStatusInternalServerError with default headers values
func NewGetAllTeachersByStatusInternalServerError() *GetAllTeachersByStatusInternalServerError {
	return &GetAllTeachersByStatusInternalServerError{}
}

/* GetAllTeachersByStatusInternalServerError describes a response with status code 500, with default header values.

服务器内部异常
*/
type GetAllTeachersByStatusInternalServerError struct {
	Payload *models.Error
}

func (o *GetAllTeachersByStatusInternalServerError) Error() string {
	return fmt.Sprintf("[GET /teachers/{teacherStatus}][%d] getAllTeachersByStatusInternalServerError  %+v", 500, o.Payload)
}
func (o *GetAllTeachersByStatusInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAllTeachersByStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetAllTeachersByStatusOKBody get all teachers by status o k body
swagger:model GetAllTeachersByStatusOKBody
*/
type GetAllTeachersByStatusOKBody struct {

	// data
	Data []string `json:"data"`

	// 对结果的描述
	// Example: 获取成功
	Msg string `json:"msg,omitempty"`

	// 结果情况, success 代表成功, 其他 代表失败
	// Example: success
	// Enum: [success fail]
	Result string `json:"result,omitempty"`
}

// Validate validates this get all teachers by status o k body
func (o *GetAllTeachersByStatusOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getAllTeachersByStatusOKBodyTypeResultPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["success","fail"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAllTeachersByStatusOKBodyTypeResultPropEnum = append(getAllTeachersByStatusOKBodyTypeResultPropEnum, v)
	}
}

const (

	// GetAllTeachersByStatusOKBodyResultSuccess captures enum value "success"
	GetAllTeachersByStatusOKBodyResultSuccess string = "success"

	// GetAllTeachersByStatusOKBodyResultFail captures enum value "fail"
	GetAllTeachersByStatusOKBodyResultFail string = "fail"
)

// prop value enum
func (o *GetAllTeachersByStatusOKBody) validateResultEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getAllTeachersByStatusOKBodyTypeResultPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetAllTeachersByStatusOKBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	// value enum
	if err := o.validateResultEnum("getAllTeachersByStatusOK"+"."+"result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get all teachers by status o k body based on context it is used
func (o *GetAllTeachersByStatusOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAllTeachersByStatusOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAllTeachersByStatusOKBody) UnmarshalBinary(b []byte) error {
	var res GetAllTeachersByStatusOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
