// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"courseWork/cmd/models"
)

// GetPlaybackInfosBySessionIdsReader is a Reader for the GetPlaybackInfosBySessionIds structure.
type GetPlaybackInfosBySessionIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPlaybackInfosBySessionIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGetPlaybackInfosBySessionIdsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetPlaybackInfosBySessionIdsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPlaybackInfosBySessionIdsCreated creates a GetPlaybackInfosBySessionIdsCreated with default headers values
func NewGetPlaybackInfosBySessionIdsCreated() *GetPlaybackInfosBySessionIdsCreated {
	return &GetPlaybackInfosBySessionIdsCreated{}
}

/* GetPlaybackInfosBySessionIdsCreated describes a response with status code 201, with default header values.

请求成功
*/
type GetPlaybackInfosBySessionIdsCreated struct {
	Payload *GetPlaybackInfosBySessionIdsCreatedBody
}

func (o *GetPlaybackInfosBySessionIdsCreated) Error() string {
	return fmt.Sprintf("[POST /playbackInfos][%d] getPlaybackInfosBySessionIdsCreated  %+v", 201, o.Payload)
}
func (o *GetPlaybackInfosBySessionIdsCreated) GetPayload() *GetPlaybackInfosBySessionIdsCreatedBody {
	return o.Payload
}

func (o *GetPlaybackInfosBySessionIdsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPlaybackInfosBySessionIdsCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPlaybackInfosBySessionIdsInternalServerError creates a GetPlaybackInfosBySessionIdsInternalServerError with default headers values
func NewGetPlaybackInfosBySessionIdsInternalServerError() *GetPlaybackInfosBySessionIdsInternalServerError {
	return &GetPlaybackInfosBySessionIdsInternalServerError{}
}

/* GetPlaybackInfosBySessionIdsInternalServerError describes a response with status code 500, with default header values.

服务器内部异常
*/
type GetPlaybackInfosBySessionIdsInternalServerError struct {
	Payload *models.Error
}

func (o *GetPlaybackInfosBySessionIdsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /playbackInfos][%d] getPlaybackInfosBySessionIdsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetPlaybackInfosBySessionIdsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetPlaybackInfosBySessionIdsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPlaybackInfosBySessionIdsCreatedBody get playback infos by session ids created body
swagger:model GetPlaybackInfosBySessionIdsCreatedBody
*/
type GetPlaybackInfosBySessionIdsCreatedBody struct {

	// data
	Data []*models.PlaybackInfo `json:"data"`

	// 对结果的描述
	// Example: 获取成功
	Msg string `json:"msg,omitempty"`

	// 结果情况, success 代表成功, 其他 代表失败
	// Example: success
	// Enum: [success fail]
	Result string `json:"result,omitempty"`
}

// Validate validates this get playback infos by session ids created body
func (o *GetPlaybackInfosBySessionIdsCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlaybackInfosBySessionIdsCreatedBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPlaybackInfosBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getPlaybackInfosBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var getPlaybackInfosBySessionIdsCreatedBodyTypeResultPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["success","fail"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getPlaybackInfosBySessionIdsCreatedBodyTypeResultPropEnum = append(getPlaybackInfosBySessionIdsCreatedBodyTypeResultPropEnum, v)
	}
}

const (

	// GetPlaybackInfosBySessionIdsCreatedBodyResultSuccess captures enum value "success"
	GetPlaybackInfosBySessionIdsCreatedBodyResultSuccess string = "success"

	// GetPlaybackInfosBySessionIdsCreatedBodyResultFail captures enum value "fail"
	GetPlaybackInfosBySessionIdsCreatedBodyResultFail string = "fail"
)

// prop value enum
func (o *GetPlaybackInfosBySessionIdsCreatedBody) validateResultEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getPlaybackInfosBySessionIdsCreatedBodyTypeResultPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetPlaybackInfosBySessionIdsCreatedBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	// value enum
	if err := o.validateResultEnum("getPlaybackInfosBySessionIdsCreated"+"."+"result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get playback infos by session ids created body based on the context it is used
func (o *GetPlaybackInfosBySessionIdsCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPlaybackInfosBySessionIdsCreatedBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPlaybackInfosBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getPlaybackInfosBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPlaybackInfosBySessionIdsCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPlaybackInfosBySessionIdsCreatedBody) UnmarshalBinary(b []byte) error {
	var res GetPlaybackInfosBySessionIdsCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
