// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"courseWork/cmd/models"
)

// NewGetSessionInfoBySessionIdsParams creates a new GetSessionInfoBySessionIdsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSessionInfoBySessionIdsParams() *GetSessionInfoBySessionIdsParams {
	return &GetSessionInfoBySessionIdsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSessionInfoBySessionIdsParamsWithTimeout creates a new GetSessionInfoBySessionIdsParams object
// with the ability to set a timeout on a request.
func NewGetSessionInfoBySessionIdsParamsWithTimeout(timeout time.Duration) *GetSessionInfoBySessionIdsParams {
	return &GetSessionInfoBySessionIdsParams{
		timeout: timeout,
	}
}

// NewGetSessionInfoBySessionIdsParamsWithContext creates a new GetSessionInfoBySessionIdsParams object
// with the ability to set a context for a request.
func NewGetSessionInfoBySessionIdsParamsWithContext(ctx context.Context) *GetSessionInfoBySessionIdsParams {
	return &GetSessionInfoBySessionIdsParams{
		Context: ctx,
	}
}

// NewGetSessionInfoBySessionIdsParamsWithHTTPClient creates a new GetSessionInfoBySessionIdsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSessionInfoBySessionIdsParamsWithHTTPClient(client *http.Client) *GetSessionInfoBySessionIdsParams {
	return &GetSessionInfoBySessionIdsParams{
		HTTPClient: client,
	}
}

/* GetSessionInfoBySessionIdsParams contains all the parameters to send to the API endpoint
   for the get session info by session ids operation.

   Typically these are written to a http.Request.
*/
type GetSessionInfoBySessionIdsParams struct {

	/* SessionIds.

	   SessionId's array
	*/
	SessionIds *models.SessionIds

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get session info by session ids params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionInfoBySessionIdsParams) WithDefaults() *GetSessionInfoBySessionIdsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get session info by session ids params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionInfoBySessionIdsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) WithTimeout(timeout time.Duration) *GetSessionInfoBySessionIdsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) WithContext(ctx context.Context) *GetSessionInfoBySessionIdsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) WithHTTPClient(client *http.Client) *GetSessionInfoBySessionIdsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSessionIds adds the sessionIds to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) WithSessionIds(sessionIds *models.SessionIds) *GetSessionInfoBySessionIdsParams {
	o.SetSessionIds(sessionIds)
	return o
}

// SetSessionIds adds the sessionIds to the get session info by session ids params
func (o *GetSessionInfoBySessionIdsParams) SetSessionIds(sessionIds *models.SessionIds) {
	o.SessionIds = sessionIds
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionInfoBySessionIdsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.SessionIds != nil {
		if err := r.SetBodyParam(o.SessionIds); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
