// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSessionInfosByRangeParams creates a new GetSessionInfosByRangeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSessionInfosByRangeParams() *GetSessionInfosByRangeParams {
	return &GetSessionInfosByRangeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSessionInfosByRangeParamsWithTimeout creates a new GetSessionInfosByRangeParams object
// with the ability to set a timeout on a request.
func NewGetSessionInfosByRangeParamsWithTimeout(timeout time.Duration) *GetSessionInfosByRangeParams {
	return &GetSessionInfosByRangeParams{
		timeout: timeout,
	}
}

// NewGetSessionInfosByRangeParamsWithContext creates a new GetSessionInfosByRangeParams object
// with the ability to set a context for a request.
func NewGetSessionInfosByRangeParamsWithContext(ctx context.Context) *GetSessionInfosByRangeParams {
	return &GetSessionInfosByRangeParams{
		Context: ctx,
	}
}

// NewGetSessionInfosByRangeParamsWithHTTPClient creates a new GetSessionInfosByRangeParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSessionInfosByRangeParamsWithHTTPClient(client *http.Client) *GetSessionInfosByRangeParams {
	return &GetSessionInfosByRangeParams{
		HTTPClient: client,
	}
}

/* GetSessionInfosByRangeParams contains all the parameters to send to the API endpoint
   for the get session infos by range operation.

   Typically these are written to a http.Request.
*/
type GetSessionInfosByRangeParams struct {

	/* End.

	   连线 开始时间的截止时间戳(unix 时间戳(毫秒))

	   Format: int64
	*/
	End int64

	/* Start.

	   连线 开始时间的起始时间戳(unix 时间戳(毫秒))

	   Format: int64
	*/
	Start int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get session infos by range params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionInfosByRangeParams) WithDefaults() *GetSessionInfosByRangeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get session infos by range params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSessionInfosByRangeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get session infos by range params
func (o *GetSessionInfosByRangeParams) WithTimeout(timeout time.Duration) *GetSessionInfosByRangeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get session infos by range params
func (o *GetSessionInfosByRangeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get session infos by range params
func (o *GetSessionInfosByRangeParams) WithContext(ctx context.Context) *GetSessionInfosByRangeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get session infos by range params
func (o *GetSessionInfosByRangeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get session infos by range params
func (o *GetSessionInfosByRangeParams) WithHTTPClient(client *http.Client) *GetSessionInfosByRangeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get session infos by range params
func (o *GetSessionInfosByRangeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEnd adds the end to the get session infos by range params
func (o *GetSessionInfosByRangeParams) WithEnd(end int64) *GetSessionInfosByRangeParams {
	o.SetEnd(end)
	return o
}

// SetEnd adds the end to the get session infos by range params
func (o *GetSessionInfosByRangeParams) SetEnd(end int64) {
	o.End = end
}

// WithStart adds the start to the get session infos by range params
func (o *GetSessionInfosByRangeParams) WithStart(start int64) *GetSessionInfosByRangeParams {
	o.SetStart(start)
	return o
}

// SetStart adds the start to the get session infos by range params
func (o *GetSessionInfosByRangeParams) SetStart(start int64) {
	o.Start = start
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionInfosByRangeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param end
	qrEnd := o.End
	qEnd := swag.FormatInt64(qrEnd)
	if qEnd != "" {

		if err := r.SetQueryParam("end", qEnd); err != nil {
			return err
		}
	}

	// query param start
	qrStart := o.Start
	qStart := swag.FormatInt64(qrStart)
	if qStart != "" {

		if err := r.SetQueryParam("start", qStart); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
