// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllTeachersByStatusParams creates a new GetAllTeachersByStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAllTeachersByStatusParams() *GetAllTeachersByStatusParams {
	return &GetAllTeachersByStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllTeachersByStatusParamsWithTimeout creates a new GetAllTeachersByStatusParams object
// with the ability to set a timeout on a request.
func NewGetAllTeachersByStatusParamsWithTimeout(timeout time.Duration) *GetAllTeachersByStatusParams {
	return &GetAllTeachersByStatusParams{
		timeout: timeout,
	}
}

// NewGetAllTeachersByStatusParamsWithContext creates a new GetAllTeachersByStatusParams object
// with the ability to set a context for a request.
func NewGetAllTeachersByStatusParamsWithContext(ctx context.Context) *GetAllTeachersByStatusParams {
	return &GetAllTeachersByStatusParams{
		Context: ctx,
	}
}

// NewGetAllTeachersByStatusParamsWithHTTPClient creates a new GetAllTeachersByStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAllTeachersByStatusParamsWithHTTPClient(client *http.Client) *GetAllTeachersByStatusParams {
	return &GetAllTeachersByStatusParams{
		HTTPClient: client,
	}
}

/* GetAllTeachersByStatusParams contains all the parameters to send to the API endpoint
   for the get all teachers by status operation.

   Typically these are written to a http.Request.
*/
type GetAllTeachersByStatusParams struct {

	/* TeacherStatus.

	   online 表示在线的老师, inClass 表示连线中的老师
	*/
	TeacherStatus string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get all teachers by status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTeachersByStatusParams) WithDefaults() *GetAllTeachersByStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get all teachers by status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAllTeachersByStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) WithTimeout(timeout time.Duration) *GetAllTeachersByStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) WithContext(ctx context.Context) *GetAllTeachersByStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) WithHTTPClient(client *http.Client) *GetAllTeachersByStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTeacherStatus adds the teacherStatus to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) WithTeacherStatus(teacherStatus string) *GetAllTeachersByStatusParams {
	o.SetTeacherStatus(teacherStatus)
	return o
}

// SetTeacherStatus adds the teacherStatus to the get all teachers by status params
func (o *GetAllTeachersByStatusParams) SetTeacherStatus(teacherStatus string) {
	o.TeacherStatus = teacherStatus
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllTeachersByStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param teacherStatus
	if err := r.SetPathParam("teacherStatus", o.TeacherStatus); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
