// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"courseWork/cmd/models"
)

// GetSessionInfoBySessionIdsReader is a Reader for the GetSessionInfoBySessionIds structure.
type GetSessionInfoBySessionIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSessionInfoBySessionIdsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewGetSessionInfoBySessionIdsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetSessionInfoBySessionIdsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetSessionInfoBySessionIdsCreated creates a GetSessionInfoBySessionIdsCreated with default headers values
func NewGetSessionInfoBySessionIdsCreated() *GetSessionInfoBySessionIdsCreated {
	return &GetSessionInfoBySessionIdsCreated{}
}

/* GetSessionInfoBySessionIdsCreated describes a response with status code 201, with default header values.

请求成功
*/
type GetSessionInfoBySessionIdsCreated struct {
	Payload *GetSessionInfoBySessionIdsCreatedBody
}

func (o *GetSessionInfoBySessionIdsCreated) Error() string {
	return fmt.Sprintf("[POST /sessionInfosBySessionIds][%d] getSessionInfoBySessionIdsCreated  %+v", 201, o.Payload)
}
func (o *GetSessionInfoBySessionIdsCreated) GetPayload() *GetSessionInfoBySessionIdsCreatedBody {
	return o.Payload
}

func (o *GetSessionInfoBySessionIdsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetSessionInfoBySessionIdsCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSessionInfoBySessionIdsInternalServerError creates a GetSessionInfoBySessionIdsInternalServerError with default headers values
func NewGetSessionInfoBySessionIdsInternalServerError() *GetSessionInfoBySessionIdsInternalServerError {
	return &GetSessionInfoBySessionIdsInternalServerError{}
}

/* GetSessionInfoBySessionIdsInternalServerError describes a response with status code 500, with default header values.

服务器内部异常
*/
type GetSessionInfoBySessionIdsInternalServerError struct {
	Payload *models.Error
}

func (o *GetSessionInfoBySessionIdsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /sessionInfosBySessionIds][%d] getSessionInfoBySessionIdsInternalServerError  %+v", 500, o.Payload)
}
func (o *GetSessionInfoBySessionIdsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetSessionInfoBySessionIdsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetSessionInfoBySessionIdsCreatedBody get session info by session ids created body
swagger:model GetSessionInfoBySessionIdsCreatedBody
*/
type GetSessionInfoBySessionIdsCreatedBody struct {

	// data
	Data []*models.SessionInfo `json:"data"`

	// 对结果的描述
	Msg string `json:"msg,omitempty"`

	// 结果情况, success 代表成功, 其他 代表失败
	// Enum: [success fail]
	Result string `json:"result,omitempty"`
}

// Validate validates this get session info by session ids created body
func (o *GetSessionInfoBySessionIdsCreatedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSessionInfoBySessionIdsCreatedBody) validateData(formats strfmt.Registry) error {
	if swag.IsZero(o.Data) { // not required
		return nil
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getSessionInfoBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getSessionInfoBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var getSessionInfoBySessionIdsCreatedBodyTypeResultPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["success","fail"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getSessionInfoBySessionIdsCreatedBodyTypeResultPropEnum = append(getSessionInfoBySessionIdsCreatedBodyTypeResultPropEnum, v)
	}
}

const (

	// GetSessionInfoBySessionIdsCreatedBodyResultSuccess captures enum value "success"
	GetSessionInfoBySessionIdsCreatedBodyResultSuccess string = "success"

	// GetSessionInfoBySessionIdsCreatedBodyResultFail captures enum value "fail"
	GetSessionInfoBySessionIdsCreatedBodyResultFail string = "fail"
)

// prop value enum
func (o *GetSessionInfoBySessionIdsCreatedBody) validateResultEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getSessionInfoBySessionIdsCreatedBodyTypeResultPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetSessionInfoBySessionIdsCreatedBody) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(o.Result) { // not required
		return nil
	}

	// value enum
	if err := o.validateResultEnum("getSessionInfoBySessionIdsCreated"+"."+"result", "body", o.Result); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this get session info by session ids created body based on the context it is used
func (o *GetSessionInfoBySessionIdsCreatedBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetSessionInfoBySessionIdsCreatedBody) contextValidateData(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {
			if err := o.Data[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getSessionInfoBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getSessionInfoBySessionIdsCreated" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetSessionInfoBySessionIdsCreatedBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetSessionInfoBySessionIdsCreatedBody) UnmarshalBinary(b []byte) error {
	var res GetSessionInfoBySessionIdsCreatedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
