// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSetPlaybackStatusToRegenerationParams creates a new SetPlaybackStatusToRegenerationParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSetPlaybackStatusToRegenerationParams() *SetPlaybackStatusToRegenerationParams {
	return &SetPlaybackStatusToRegenerationParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSetPlaybackStatusToRegenerationParamsWithTimeout creates a new SetPlaybackStatusToRegenerationParams object
// with the ability to set a timeout on a request.
func NewSetPlaybackStatusToRegenerationParamsWithTimeout(timeout time.Duration) *SetPlaybackStatusToRegenerationParams {
	return &SetPlaybackStatusToRegenerationParams{
		timeout: timeout,
	}
}

// NewSetPlaybackStatusToRegenerationParamsWithContext creates a new SetPlaybackStatusToRegenerationParams object
// with the ability to set a context for a request.
func NewSetPlaybackStatusToRegenerationParamsWithContext(ctx context.Context) *SetPlaybackStatusToRegenerationParams {
	return &SetPlaybackStatusToRegenerationParams{
		Context: ctx,
	}
}

// NewSetPlaybackStatusToRegenerationParamsWithHTTPClient creates a new SetPlaybackStatusToRegenerationParams object
// with the ability to set a custom HTTPClient for a request.
func NewSetPlaybackStatusToRegenerationParamsWithHTTPClient(client *http.Client) *SetPlaybackStatusToRegenerationParams {
	return &SetPlaybackStatusToRegenerationParams{
		HTTPClient: client,
	}
}

/* SetPlaybackStatusToRegenerationParams contains all the parameters to send to the API endpoint
   for the set playback status to regeneration operation.

   Typically these are written to a http.Request.
*/
type SetPlaybackStatusToRegenerationParams struct {

	/* SessionID.

	   连线 ID
	*/
	SessionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the set playback status to regeneration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetPlaybackStatusToRegenerationParams) WithDefaults() *SetPlaybackStatusToRegenerationParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the set playback status to regeneration params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SetPlaybackStatusToRegenerationParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) WithTimeout(timeout time.Duration) *SetPlaybackStatusToRegenerationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) WithContext(ctx context.Context) *SetPlaybackStatusToRegenerationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) WithHTTPClient(client *http.Client) *SetPlaybackStatusToRegenerationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSessionID adds the sessionID to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) WithSessionID(sessionID string) *SetPlaybackStatusToRegenerationParams {
	o.SetSessionID(sessionID)
	return o
}

// SetSessionID adds the sessionId to the set playback status to regeneration params
func (o *SetPlaybackStatusToRegenerationParams) SetSessionID(sessionID string) {
	o.SessionID = sessionID
}

// WriteToRequest writes these params to a swagger request
func (o *SetPlaybackStatusToRegenerationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param sessionId
	if err := r.SetPathParam("sessionId", o.SessionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
